### ISSUE TITLE
kumactl apply and Kuberentes

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#165]
When `kumactl` tries to `apply` on a Kuma cluster that runs on Kubernetes, block the operation with a user-friendly message.

**Comment by jakubdyszkiewicz** [comment]
Modification operations with Kuma on Kubernetes should be done with `kubectl`. That's why we run API Server in read-only mode
https://github.com/Kong/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L154
When API Server is run in read-only mode we just do not register PUT/DELETE endpoints
https://github.com/Kong/kuma/blob/master/pkg/api-server/server.go#L111

The goal of this task is to inform this user when he tries to use `kumactl` when running on K8S.

To replicate:
1) Run Kuma on K8S
2) Port-forward 5681
3) Try to run
```
$ echo "type: Mesh
name: default" | ./kumactl apply -f -
```

I see two ways to go with this task
1) Either check the environment (probably by requesting `/config` endpoint of CP) on kumactl side and return a friendly error message if this is K8S
2) When running on K8S, instead of not registering PUT/DELETE endpoint, register them but they will always return a friendly error

Second seems better because it works outside of only kumactl.

**Comment by subnetmarco** [comment]
When trying to change the state with `kumactl` on Kubernetes, return a friendly message that suggests to use use `kubectl` instead, like:

```
on Kubernetes you cannot change the state of Kuma resources with "kumactl apply" and as a best practice you should be using "kubectl apply" instead; you can still use kumactl to make read-only operations. On Universal this limitation does not apply.
```
