### ISSUE TITLE
When generating Envoy configuration, any relevant Kuma resources must be loaded from cache

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#278]
### Summary

* at the moment, when generating Envoy configuration we use `ResourceManager` API to `List` and `Get` individual `Kuma` resources
* while on `k8s` it is already efficient (due to a caching layer that is part of `controller-runtime`), in `universal` case it implies extra DB queries that could be avoided

**Comment by jakubdyszkiewicz** [comment]
# Implementation proposal

Create/Update operations of `ResourceManager` are executed in following scenarios:
* REST API
* Create default mesh
* Dataplane status sink (`DataplaneInsight` entity)

Delete:
* REST API
* Mesh Controller to remove leftovers of mesh

We don't want to introduce distributed cache like Redis to not to complicate deployment. Instead we want to use local in memory cache.

The main problem is that every Dataplane has their own goroutine with refresh rate of X seconds (1s by default). Assuming that Snapshot generation logic will execute 10 requests to ResourceStore (retrieving dp, computing which resources apply etc.) - 1,000 DPs will execute 10,000 rps. If we cache resources, we can reduce it to 1,000 rps.

Because there are not many CREATE/UPDATE/DELETE outside of REST API, the cache can be simple:
We can write wrapper over ResourceStore.
The key of the cache is resource type + GetOptionsOpts or resource type + ListOptionsOpts.
When there is CREATE/UPDATE/DELETE operation on given type, we wipe out cache for this type with any combination of GetOptionsFunc/ListOptionsFunc for the simplicity.

Items in cache will live for a short period of time. This time should be shorter than 2x `DataplaneConfigurationRefreshInterval`, otherwise we will waste cpu computing snapshot with the same set of resources.

For the REST API we can either acknowledge that responses from 2 different instances can be inconsistent for this short period of time, or we can use there non-cached store there, since the main load to ResourceStore is Envoy snapshot generator, not managing API.

@yskopets WDYT?

**Comment by jakubdyszkiewicz** [comment]
Done in 0.4.x
