### ISSUE TITLE
how to use "outbound"?

### ISSUE THREAD

**Issue by fyuck** [Kong/kuma#292]
i got 2 vm to deploy the universal mode mesh and the configs:
in vm1:
echo "type: Dataplane
mesh: default
name: dp-echo-1
networking:
  inbound:
  - interface: 127.0.0.1:11152:10152
    tags:
      service: echo” | kumactl apply -f -

and run dp like this:
`KUMA_CONTROL_PLANE_BOOTSTRAP_SERVER_URL=http://127.0.0.1:5682 \
KUMA_DATAPLANE_MESH=default \
KUMA_DATAPLANE_NAME=dp-echo-1 \
KUMA_DATAPLANE_ADMIN_PORT=9901 \
kuma-dp run`

in vm2:

`echo "type: Dataplane
mesh: default                                                                   
name: dp-echo-2
networking:
  inbound:
  - interface: 127.0.0.1:11153:10153
    tags:
      service: echo2
  outbound:
  - interface: :11152
    service: echo" | kumactl apply -f -`

`KUMA_CONTROL_PLANE_BOOTSTRAP_SERVER_URL=http://127.0.0.1:5682 \
KUMA_DATAPLANE_MESH=default \
KUMA_DATAPLANE_NAME=dp-echo-2 \
KUMA_DATAPLANE_ADMIN_PORT=9901 \
kuma-dp run`

each vm runs a nginx and nginx in vm2 has the config to proxy_pass to vm1.
    location ^~ /aaa {
         proxy_pass   http://vm1:11152;
    }

    location ^~ /bbb {
         proxy_pass   http://127.0.0.1:11152;
    }
the port 11152 and 11153 listening is ok .
my question is how to use outbound?/aaa and /bbb dont work,
i dont know if my kuma config has something wrong or my nginx config has something wrong
need help,thx

**Comment by yskopets** [comment]
@fyuck Hi!

For a `Dataplane` to be reachable from other hosts it must have an inbound interface listening on a non-loopback IP.

E.g., `dp-echo-1` in your example should have the inbound interface similar to `192.168.0.1:11152:10152` rather than `127.0.0.1:11152:10152` (notice `192.168.0.1` instead of `127.0.0.1`).

* In that case, `Dataplane` would be listening on `192.168.0.1:11152` and forwarding traffic to `127.0.0.1:10152`

Also, notice that in your example both `Dataplanes` connect to the Control Plane using loopback address (namely, `KUMA_CONTROL_PLANE_BOOTSTRAP_SERVER_URL=http://127.0.0.1:5682`).

Are you running multiple instances of the Control Plane ? Are you using Postgres to make sure the configuration is in sync ?

**Comment by fyuck** [comment]
@yskopets thanks a lot,it works now!
Are you running multiple instances of the Control Plane ? Are you using Postgres to make sure the configuration is in sync ?
i am running 2 cp in each vm and using memory

and how can i use outbound?
outbound port 11152 is listening in vm2

**Comment by yskopets** [comment]
@fyuck 

Both `Dataplanes` must be connected to the same Control Plane:

* it can be a single Control Plane instance configured with `in-memory` configuration store
* it can be separate Control Plane instances configured with `postgres` configuration store (so that they share configuration)

Once both `Dataplanes` are connected to the same Control Plane, outgoing traffic will be dispatched according to `outbound networking` section.

E.g., in your example

```
type: Dataplane
mesh: default
name: dp-echo-2
networking:
  outbound:
  - interface: :11152
     service: echo
``` 

the behaviour will be the following:

* `dp-echo-2` will be listening on `127.0.0.1:11152` on `vm2`
* all traffic received on `127.0.0.1:11152` of `vm2` will be dispatched to `Dataplanes` with tag `service: echo` on their inbound interface (e.g., to `interface: <NON-LOOPBACK IP>:11152:10152` of `dp-echo-1`)

So, to use outbound you need to have an application running `vm2` and making requests to `127.0.0.1:11152`

**Comment by fyuck** [comment]
@yskopets 
thx a lot!it's ok now
