### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#515]
### Summary

Our DB model is "thin" since we've got only one table and store resource specs as json. During the development we had to change it, so there is high chance that we will need to do it again. We should provide mechanism to do the migration.

### Implementation proposal

There will be a table called `migrations` in Postgres schema with versioning:
```
VERSION
0
```
Then when applying migration, we can check current applied version in DB and apply new one if there is any.

All migration files will be stored with following convention:
```
{version}.{name_with_description}.up.sql
{version}.{name_with_description}.down.sql
```
Every migration should have rollback migration.

There are two ways how migration can be applied
1) Auto migration when instance with new version of Kuma starts. It applies migrations if necessary.
2) `kuma-cp migrate` command that explicitly needs to be run before starting new version of `kuma-cp`. CP won't start if there is incompatible version of the schema.

### Rollbacks
There should be a way to rollback schema to older version if downgrade of Kuma is needed.
To do that, user will run `kuma-cp migrate --version=0.3.0`.

**Comment by dhruv** [comment]
@subnetmarco Can we get your feedback on this please?

**Comment by subnetmarco** [comment]
> kuma-cp migrate command that explicitly needs to be run before starting new version of kuma-cp. CP won't start if there is incompatible version of the schema.

I prefer this.

Also @jakubdyszkiewicz please chat with @hishamhm and @thibaultcha since they have built something similar in Kong, and you can share lessons learned so we don't repeat the same mistakes with Kuma.

**Comment by hishamhm** [comment]
Some quick pieces of feedback from the development history of Kong's migrations:

> There will be a table called migrations in Postgres schema with versioning:

In Kong, the migrations table keeps a list of migrations executed, and not just a version. This is useful if there's ever a chance you could end up in an intermediate state. If you only ever support Postgres and all your migrations are always pure SQL, then you can run everything in a transaction and you'll never get an intermediate state. But if you ever support a different DB without transactions (knock on wood!) or if you find yourself having to do some processing via code in between migrations (more likely to happen if your data model grows complex), then being able to know if a migration failed halfway through will be useful.

Another use-case for that is if you ever have different flavors of Kuma (like we do with Kong and Kong Enterprise). Your versions history then are no longer a single linear flow, but can branch out into another flavor at any point.

> There should be a way to rollback schema to older version if downgrade of Kuma is needed.

While this is a noble goal, in our experience we found that nobody ever used this. We had `up` and `down` in Kong 0.x, but at one point many `down` migrations were broken because they weren't really tested or even missing because nobody really cared and no users complained. In Kong 1.0 we removed the `down` migrations altogether. Nobody has asked for it since.

I'd spare the effort in Kuma — just do it if you have to. Rolling back can get super tricky depending on the data transformations you apply moving forward (in the worst cases, you'd have to keep some old data around just for the sake of rollback).

One other thing we _did_ add in Kong migrations is that we've been trying hard lately to write the SQL for migrations in an idempotent way: you should be able to run the SQL twice and have the second run not fail (everything has `IF NOT EXISTS`, etc.). The goal is tho make things more resilient (for the same two reasons as the migrations list above: it's easier to retry migrations if not using a transaction, and it's useful in the face of multiple flavors, as their migrations don't need to be in perfect lockstep — it's okay if the flavor's additions redo something that the base migration already did, it makes for easier maintenance). It's not always feasible to ensure full idempotence, but it doesn't hurt to add those `IF NOT EXISTS` checks.
